---
- hosts: webservers
  become: yes
  tasks:
    - name: install webserver
      apt:
       name: "{{webserveronUbuntu}}"
       state: present
    - name: start webserver
      service:
        name: "{{webserveronUbuntu}}"
        state: start
   
    - name: install webserver
      yum:
        name: "{{webserveronamazon}}"
        state: present
    - name: start webserver
      service:
        name: "{{webserveronamazon}}"
        state: start
   
    - name: install webserver
      yum:
        name: "{{webserveronamazon}}"
        state: present
    - name: start webserver
      service:
        name: "{{webserveronamazon}}"
        state: start