---
- hosts: webservers
  become: yes
  tasks:
    - name: install webserver
      apt:
       name: apache2
       state: present
    - name: start webserver
      service:
        name: apache2
        state: start
   
    - name: install webserver
      yum:
        name: httpd
        state: present
    - name: start webserver
      service:
        name: apache2
        state: start
   
    - name: install webserver
      yum:
        name: httpd
        state: present
    - name: start webserver
      service:
        name: apache2
        state: start