---
- hosts: webservers
  become: yes
  tasks:
  - name: install webserver
    apt:
      name: apache2
      state: present
  - name: start webserver
    service:
      name: apache2
      state: started
  - name: install tree
    apt:
       name: tree
       state: present
