---
- hosts: webservers
  become: yes
  tasks:
    - name: install webserver on Linux
      yum:
       name: "{{webserveronLinux}}"
       state: present
    - name: start webserver on Linux
      service:
        name: "{{webserveronLinux}}"
        state: start
      when: ansible_os_family=="Linux"
      ignore_errors: yes

    - name: install webserver on RedHat
      yum:
        name: "{{webserveronamazon}}"
        state: present
    - name: start webserver on RedHat
      service:
        name: "{{webserveronamazon}}"
        state: start
      when: ansible_os_family =="RedHat"