---
- hosts: webservers
  become: yes
  tasks:
 
  - name: install webserver
    yum:
      name: "{{webserveronamazon}}"
      state: present
  - name: start webserver
    service:
      name: "{{webserveronamazon}}"
      state: started
   
  - name: install webserver
    yum:
      name: "{{webserveronamazon}}"
      state: present
  - name: start webserver
    service:
      name: "{{webserveronamazon}}"
      state: started
   
  - name: install webserver
    apt:
      name: "{{webserveronubuntu}}"
      state: present
  - name: start webserver
    service:
      name: "{{webserveronubuntu}}"
      state: started

    

