---
- hosts: webservers
  become: yes
  tasks:
 
  - name: install webserver
    yum:
      name: "{{webserveronamazon}}"
      state: present
  - name: start webserver
    service:
      name: "{{webserveronamazon}}"
      state: started
    when: ansible_os_family =="amazon"

  - name: install webserver
    yum:
      name: "{{webserveronamazon}}"
      state: present
  - name: start webserver
    service:
      name: "{{webserveronamazon}}"
      state: started
    when: ansible_os_family =="RedHat"
  
  - name: install webserver
    apt:
      name: "{{webserveronubuntu}}"
      state: present
  - name: start webserver
    service:
      name: "{{webserveronubuntu}}"
      state: started
    when: ansible_os_family =="Debian"


    

