---
- hosts: localhost
  become: yes
  tasks:
  - name: create ansible nodes
    ec2:
      key_name: key
      instance_type: t2.micro
      image: ami-00d4e9ff62bc40e03
      wait: yes
      region: us-east-1a
      group: default
      count: 1
      vpc_subnet_id: subnet-696c3047
      assign_public_ip: yes
      instance_tags:
        Name: testnodes