---
# tasks file for mytomcat
 
- name: install tomcat
  apt:
    name: tomcat7
    state: present

- name: copy the config files
  template:
    src: templates/mytomconfig.j2
    dest: /etc/default/tomcat7
  notify: restarttomcat  

- name: install admin packages
  apt:
    name: "{{item}}"
    state: present
  loop:
    - tomcat7-docs
    - tomcat7-admin
    - tomcat7-examples

- name: copy the user files
  template:
    src: templates/mytomusers.j2
    dest: /etc/tomcat7/tomcat-users.xml
  notify: restarttomcat